# Generated by Django 4.1.1 on 2022-09-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'Firm')},
        ),
    ]
