# Generated by Django 4.1.1 on 2022-09-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFirm', to='DashboardApp.firm'),
        ),
    ]
