# Generated by Django 4.1.1 on 2022-09-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_alter_user_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionProduct', to='DashboardApp.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactionUser', to='DashboardApp.user'),
        ),
    ]
