# Generated by Django 4.1.1 on 2022-09-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_alter_transaction_product_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.firm'),
        ),
    ]
